### PR TITLE
Upgrade to Create React App

### LINKED ISSUE #18: Upgrade to create-react-app V2
See what was done in fssk-laravel.

### PR DESCRIPTION
**Pull request by jpchip**
Use https://github.com/facebook/create-react-app instead of https://github.com/wmonk/create-react-app-typescript/

Resolves #18

### CODE REVIEW

**Comment by aperinovic** [comment]
The client app will not boot in my docker container with this change, but it loads fine when run directly in my host OS (Mac). Could you please try destroying the containers and rebuilding from scratch to make sure it still works?

If you do that and you're not seeing the issue, could you tell me what OS you're on? If I remember correctly, it's windows; if that's the case, before I debug it I might ask someone else on a Mac to just spin it up and see if they share the issue.

**Comment by jpchip** [comment]
I am on windows, but I will give it refresh and see what happens

**Comment by jpchip** [comment]
ok, should be good to retest

**Comment by allison-buhler** [comment]
Looks good to me!

**Pull request merged**
